# Generated by Django 6.0 on 2025-12-24 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Baseboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('identifier', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('warning', 'Warning'), ('error', 'Error')], default='offline', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('mqtt_topic', models.CharField(blank=True, max_length=200)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('uptime', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100)),
                ('event_type', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], default='info', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('acknowledged', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Actuator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('actuator_type', models.CharField(choices=[('pwm', 'PWM'), ('relay', 'Relay'), ('servo', 'Servo'), ('motor', 'Motor'), ('linear', 'Linear Actuator'), ('solenoid', 'Solenoid'), ('custom', 'Custom')], max_length=20)),
                ('actuator_id', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('running', 'Running'), ('stopped', 'Stopped'), ('idle', 'Idle'), ('holding', 'Holding'), ('locked', 'Locked'), ('disconnected', 'Disconnected'), ('error', 'Error')], default='idle', max_length=20)),
                ('current_value', models.FloatField(blank=True, null=True)),
                ('min_value', models.FloatField(default=0)),
                ('max_value', models.FloatField(default=100)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('last_command', models.CharField(blank=True, max_length=100)),
                ('last_command_time', models.DateTimeField(blank=True, null=True)),
                ('last_command_latency', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('baseboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actuators', to='api.baseboard')),
            ],
            options={
                'ordering': ['baseboard', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sensor_type', models.CharField(choices=[('temperature', 'Temperature'), ('humidity', 'Humidity'), ('pressure', 'Pressure'), ('vibration', 'Vibration'), ('light', 'Light Level'), ('power', 'Power Meter'), ('gas', 'Gas Sensor'), ('motion', 'Motion'), ('custom', 'Custom')], max_length=20)),
                ('i2c_address', models.CharField(blank=True, max_length=10)),
                ('adapter_id', models.CharField(blank=True, max_length=20)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('current_value', models.FloatField(blank=True, null=True)),
                ('min_threshold', models.FloatField(blank=True, null=True)),
                ('max_threshold', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('warning', 'Warning'), ('critical', 'Critical'), ('offline', 'Offline')], default='inactive', max_length=20)),
                ('rate_of_change', models.CharField(blank=True, max_length=20)),
                ('last_reading', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('baseboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='api.baseboard')),
            ],
            options={
                'ordering': ['baseboard', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='api.sensor')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['sensor', '-timestamp'], name='api_sensorr_sensor__a96b2b_idx')],
            },
        ),
    ]
