# Generated by Django 6.0 on 2025-12-27 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actuator',
            name='i2c_address',
            field=models.CharField(blank=True, help_text='I2C address in hex, e.g., 0x08', max_length=10),
        ),
        migrations.AlterField(
            model_name='actuator',
            name='actuator_type',
            field=models.CharField(choices=[('led', 'LED'), ('pwm', 'PWM'), ('relay', 'Relay'), ('servo', 'Servo'), ('motor', 'Motor'), ('linear', 'Linear Actuator'), ('solenoid', 'Solenoid'), ('buzzer', 'Buzzer'), ('display', 'Display'), ('custom', 'Custom')], max_length=20),
        ),
        migrations.AlterField(
            model_name='actuator',
            name='status',
            field=models.CharField(choices=[('on', 'On'), ('off', 'Off'), ('running', 'Running'), ('stopped', 'Stopped'), ('idle', 'Idle'), ('holding', 'Holding'), ('locked', 'Locked'), ('disconnected', 'Disconnected'), ('error', 'Error')], default='off', max_length=20),
        ),
    ]
